[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'pallets/ocw-circuits/',
  'pallets/ocw-garble/',
  'runtime',
  'ocw-common'
]

# [package]
# name = "fakeroot"
# version = "0.0.1"
